POST http://localhost:9000/residents/8/relationship HTTP/1.1
Content-Type: application/json

{
  "familyResidentSerialNumber": 10,
  "familyRelationshipCode": "Child"
}

###

PUT http://localhost:9000/residents/8/relationship/10 HTTP/1.1
Content-Type: application/json

{
    "familyRelationshipCode": "Child"
}