POST http://localhost:9000/residents HTTP/1.1
Content-Type: application/json

{
  "name": "코트니 러브",
  "genderCode": "여",
  "birthDate": "1964-07-09 11:20:20",
  "birthPlaceCode": "자택",
  "registrationBaseAddress": "인천광역시 계양구 하늘길 112"
}

###

PUT http://localhost:9000/residents/10 HTTP/1.1
Content-Type: application/json

{
  "genderCode": "남"
}


