#한 개의 쿼리 파라미터 요청
GET http://localhost:9090/department-members?departmentId= L1002
Accept: application/json

###

#여러 개의 쿼리 파라미터 요청
GET http://localhost:9090/department-members?departmentId= L1002, L1001
Accept: application/json

###

#여러 개의 쿼리 파라미터 요청 & 인자 중 하나는 테이블에 없는 값 (L1006)이므로 L1002의 결과만 출력
GET http://localhost:9090/department-members?departmentId= L1002, L1006
Accept: application/json

###

#인자로 departmentId를 넘기지 않는 경우 400 응답
GET http://localhost:9090/department-members
Accept: application/json

###

#Accept: application/json을 설정하지 않는 경우 400 응답
GET http://localhost:9090/department-members



