POST /residents

{
    "familySerialNumber": 123,                  // 대상 가족의 주민 일련번호
    "relationShip": "father"                    // 부(father),모(mother),배우자(spouse),자녀(child)

    "name": "데이브"
    "residentRegistrationNumber": "690114-1234567"
    "genderCode": "남"
    "birthDate": "1969.01.14"
    "birthPlaceCode":
    "registrationBaseAddress":

    private final Long residentSerialNumber;
    private final String name;
    private final String residentRegistrationNumber;
    private final String genderCode;
    private final LocalDate birthDate;
    private final String birthPlaceCode;
    private final String registrationBaseAddress;
}